# 网站配置
Config: 
  title: Tabox # 网页标题
  logo: favicon.svg # logo 可以为 url
  hide: true # 隐藏侧栏
  link: https://tab.fzf404.top # Logo 跳转网页

# 搜索栏设置
Search: 
  Normal: # 搜索组 1
    Baidu: https://www.baidu.com/s?wd=
    Google: https://www.google.com/search?q=
    Bing: https://cn.bing.com/search?q=
    Translate: https://translate.google.cn/?text=

  Code:
    Github: https://github.com/search?q=
    Npm: https://www.npmjs.com/search?q=
    DockerHub: https://hub.docker.com/search?q=
    StackOF: https://stackoverflow.com/search?q=

  Community:
    Zhihu: https://www.zhihu.com/search?q=
    Juejin: https://juejin.im/search?query=
    Bilibili: https://search.bilibili.com/all?keyword=
    CSDN: https://so.csdn.net/so/search?q=

  Tools:
    Greasyfork: https://greasyfork.org/zh-CN/scripts?q=
    Choco: https://chocolatey.org/packages?q=

  Art:
    Iconfont: https://www.iconfont.cn/search?q=
    Pexels: https://www.pexels.com/search/

# 标签组
Tabox:
  Common: # 标签组 1
    # 推荐使用 https://worldvectorlogo.com/
    logo: https://cdn.worldvectorlogo.com/logos/onenote-2.svg
    description: 常用网站

    BiliBili:
      - https://www.bilibili.com
      - 年轻人的社区
      # 默认获取 https://www.bilibili.com/favicon.ico
    Taobao:
      - https://www.taobao.com
      - 掏包网
    Zhihu:
      - https://www.zhihu.com
      - 问答社区
    Wiki:
      - https://zh.wikipedia.org
      - 维基百科
      - https://static.cdnlogo.com/logos/w/74/wikipedia.svg
    Douban:
      - https://www.douban.com
      - 豆瓣网
    Weibo:
      - https://www.weibo.com
      - 微博
    Tieba:
      - https://tieba.baidu.com
      - 百度贴吧
      - https://tb3.bdstatic.com/public/icon/favicon-v2.ico
    Amap:   
      - https://ditu.amap.com/
      - 高德地图

  Website: # 标签组 2
    logo: https://cdn.worldvectorlogo.com/logos/microsoft-access-1.svg
    description: 我的网站

    Home:
      - https://www.fzf404.top
      - 我的首页
      - https://s2.loli.net/2022/04/25/yns7EGBSRTJjiHa.png
    Note:
      - https://note.fzf404.top
      - 笔记博客
      - https://s2.loli.net/2022/04/25/yns7EGBSRTJjiHa.png
    Blog:
      - https://blog.fzf404.top
      - 写作博客
      - https://s2.loli.net/2022/04/25/yns7EGBSRTJjiHa.png
    Share:
      - https://share.fzf404.top
      - 教案分享
      - https://s2.loli.net/2022/04/25/yns7EGBSRTJjiHa.png
    Tabox:
      - https://tab.fzf404.top
      - 标签页
      - https://s2.loli.net/2022/04/25/yns7EGBSRTJjiHa.png
    Server:
      - http://server.fzf404.top
      - 好用的服务
      - https://s2.loli.net/2022/04/25/yns7EGBSRTJjiHa.png
      
  Github: # github 配置
    logo: https://cdn.worldvectorlogo.com/logos/powerpoint-2.svg
    description: 我的代码仓库

    name: fzf404 # 写入自己的用户名

    # 忽略的仓库
    Ignore:
      - BPY
      - blog-comment
      - DjangoTemp
      - ExpressTemp
      - fzf404
      - rdt-editor
      - demo
      - intro
      - tools
    
  Develop:
    logo: https://cdn.worldvectorlogo.com/logos/excel-4.svg
    description: 开发社区

    Github:
      - https://github.com
      - 代码托管
    Juejin:
      - https://juejin.cn
      - 掘金社区

  Tools:
    logo: https://cdn.worldvectorlogo.com/logos/outlook-1.svg
    description: 开发工具

    Colab:
      - https://colab.research.google.com
      - 机器学习
      - https://static.cdnlogo.com/logos/p/3/python.svg

  Docs:
    logo: https://cdn.worldvectorlogo.com/logos/word-1.svg
    description: 开发文档

    Runoob:
      - https://www.runoob.com
      - 菜鸟教程
    MDN:
      - https://developer.mozilla.org/zh-CN
      - MDN 文档

  Memo: # 备忘录
    logo: https://cdn.worldvectorlogo.com/logos/microsoft-teams-1.svg
    description: 备忘录

    content: |
      Hello, This is fzf404.
      A full stack developer.
      Here is my website: 
        https://www.fzf404.top

